#:schema node_modules/wrangler/config-schema.json
name = "mailman"
main = "src/index.ts"
compatibility_date = "2024-06-03"
node_compat = true

send_email = [
  { name = "SEB" }
]

[vars]
SENDER = ""
RECIPIENT = ""